### ISSUE TITLE
[QUESTION] conclude_prompt的用途

### ISSUE THREAD

**Issue by linjt325** [chatchat-space/Langchain-Chatchat#4648]
**问题描述 / Problem Description**
在settings.py的ToolSettings中 看到知识库工具和网络搜索的配置参数有conclude_prompt, 但是没有找到相关的代码. 请问自定义总结提示词功能是否已实现? 

```
search_local_knowledgebase:
  use: false
  top_k: 3
  score_threshold: 2.0
  conclude_prompt:
    with_result: "<指令>根据已知信息，简洁和专业的来回答问题。如果无法从中得到答案，请说 \"根据已知信息无法回答该问题\"，不允许在答案中添加编造成分，答案请使用中文。
      </指令>\n<已知信息>{{ context }}</已知信息>\n<问题>{{ question }}</问题>\n"
    without_result: "请你根据我的提问回答我的问题:\n{{ question }}\n请注意，你必须在回答结束后强调，你的回答是根据你的经验回答而不是参考资料回答的。\n"
```
