### ISSUE TITLE
请问text2sql中的模型应该怎么配置

### ISSUE THREAD

**Issue by lemon3853** [chatchat-space/Langchain-Chatchat#4652]
如题，配置文件如下。如果要使用本地模型的话，这里的model_name应该怎么配置
```
text2sql:
  model_name: 
  use: false
  sqlalchemy_connect_str: postgresql+psycopg2://postgres:xxx@0.0.0.0/xxx
  read_only: false
  top_k: 50
  return_intermediate_steps: true
  table_names: []
  table_comments: {}
```
